services:
  hooky-registry:
    # build:
    #   context: src/
    #   dockerfile: docker/Dockerfile
    image: ghcr.io/hnrobert/hooky-registry:latest
    container_name: hooky-registry
    restart: unless-stopped
    environment:
      - REGISTRY=127.0.0.1:5000
      - WEBHOOK_PORT=5001
      - UPDATE_STRATEGY=recreate # Options: 'recreate' or 'restart'
    ports:
      - '5000:5000' # Registry port
      - '5001:5001' # Webhook port
    volumes:
      - registry-data:/var/lib/registry
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  registry-data:
    external: true
