[supervisord]
nodaemon=true
user=root
pidfile=/var/run/supervisord.pid
logfile=/var/log/supervisor/supervisord.log
childlogdir=/var/log/supervisor

[program:registry]
command=/entrypoint.sh /etc/docker/registry/config.yml
directory=/
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/registry.log
stderr_logfile=/var/log/supervisor/registry.log

[program:webhook-receiver]
command=/usr/local/bin/webhook-receiver
directory=/
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/webhook.log
stderr_logfile=/var/log/supervisor/webhook.log